// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: process.env["DATABASE_URL"],
    // `prisma migrate dev` needs a scratch database to detect drift. On a managed
    // instance (RDS) the migrate user may not be allowed to CREATE DATABASE, and
    // `prisma dev` exposes its shadow database on a separate port — so when
    // SHADOW_DATABASE_URL is set, use it instead of letting Prisma create one.
    shadowDatabaseUrl: process.env["SHADOW_DATABASE_URL"],
  },
});
